# Generated by Django 4.1.5 on 2023-05-25 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_delete_jobs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_logo',
            field=models.ImageField(default='', upload_to='jobs/images'),
        ),
    ]
